# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-01 12:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
